### PR TITLE
Add a -y/--assumeyes option to 'ipbb ipbus gendecoders'

### PR DESCRIPTION
**Pull request by jhegeman**
That way (just like yum does) one can skip the question about whether
or not to update the address tables. The assumption is, of course,
that one only calls gendecoders if one wants to update the address
decoders. This flag will allow automation.

### CODE REVIEW

**Comment by alessandrothea** [comment]
Hi again and thanks again.
This is fine, I just have a small request: can the flag be renamed `-f/--force` for consistency with other similar options?

Thanks!

**Comment by jhegeman** [comment]
> This is fine, I just have a small request: can the flag be renamed `-f/--force` for consistency with other similar options?

Are you sure? This does not really force anything. It simply assumes that the user will answer 'yes'. That's why I copied the naming from the yum -y option.

If you confirm that you really want it to be --force, I will change it though.

**Comment by alessandrothea** [comment]
It's a bit of an arbitrary choice, of course.
Both `-y/--yes` and -`f/--force` are used for this purpose by different applications. `rm` uses `-f`, for instance.
At some point I settled with `-f` for ipbb commands which overwrite existing files, so I'd rather use that everywhere.

**Comment by alessandrothea** [comment]
Run tests

**Pull request merged**
