### PR TITLE
Cc8 and python3 fixes

### PR DESCRIPTION
**Pull request by jhegeman**
These are a few (minor) changes that are required to make things work on CC8 (with Python3). I won't claim that these are all required changes, but they are enough to make my workflow work again. (And I'm not set up to test outside my workflow, really.)

### CODE REVIEW

**Review by jhegeman — COMMENTED** [review]
On CC8 there is _no_ /usr/bin/python... (obviously)

**Comment by alessandrothea** [comment]
Run tests

**Comment by alessandrothea** [comment]
Many thanks @jhegeman. Some of these issues should have been caught by the ci, if I hadn't been too lazy to get it fully to work on Centos8. I'll fix that now.

How's Centos8 working for you? I haven't had the time to give it a spin, yet.

**Comment by jhegeman** [comment]
Hi @alessandrothea,

> How's Centos8 working for you? I haven't had the time to give it a spin, yet.

I have not made the full transition yet, but I upgraded one of my lab development machines to CC8. The local network services (DHCP, RARPD, BIND, etc.) I have not yet migrated. They still run on a CC7 machine.

As far as development and desktop work goes the transition was quite smooth, to be honest. There are of course the usual details with different versions of ssh, tmux, etc. But the real reason these things are tricky to handle is because one wants to keep using CC7 and CC8 machines in parallel. Otherwise I have not found anything that really does not work.

Jeroen

**Pull request merged**
